<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Promise</title>
    </head>
    <body>
        <h1>Реализация промиса</h1>
        <h2>Особенности промиса</h2>
        <ol>
            <li>Промис может менять состояние только <b>один</b> раз -
                 то есть результатом может стать либо resolve, либо reject, выполненный один раз.</li>
            <li>Функция-executor выполняется <b>синхронно</b>. Если ф-ция-executor не содержит асинхронных операций, то resolve/reject также вызовется синхронно.</li>
            <li>Функция resolve/reject чаще всего вызывается <b>асинхронно</b>(setTimeout, fetch),
                 поэтому получить результат выполнения промиса можно тоже только асинхронно.</li>
            <li>Метод 'then' принимает на вход 2 коллбэка: 
                <ol>
                    <li>На случай, если промис завершен успешно.</li>
                    <li>На случай, если промис завершен с ошибкой.</li>
                </ol>
                Однако, зачастую в then передают только первый колбэк, оставляя обработку ошибок блоку catch.
            </li>
        </ol>
        <script type="module" src="../src/index.js"></script>
    </body>
</html>